Add config API
yunity/karrot-backend pull request #1116
Opened 2021-02-15 23:56 UTC by nicksellen

The idea with this is to put all the configuration for frontend in the backend configuration file rather than baked into the frontend build.

Currently we include FCM and Sentry configuration details baked into the build, this means it's not possible to set them yourself without building your own custom version.

This changes it so karrot deployment configuration is all in one env file on the server.

This adds an `/api/config/` endpoint, and also provides the same data via `/api/bootstrap/` under the key `config`.

The reason I made it available at two endpoints is so the service worker can request it without all the other bootstrap stuff. Although maybe I can send the bootstrap data from the main app to it. I get a bit confused with the service worker stuff.

2021-05-10 20:41 UTC, layla19 requested changes

2021-05-10 21:13 UTC, nicksellen commented on sync.py
> +    return subprocess.run(['grep', 'docker', '/proc/1/cgroup'], stdout=subprocess.DEVNULL).returncode == 0
Thanks, much nicer!

I do actually wonder if my assumption for adding this in the first place is right, doing git-stuff outside the container, and so not installing pre-commit inside? Or would you do your git-stuff inside the container too? ... both have their drawbacks.

2021-05-10 21:14 UTC, nicksellen commented on karrot/bootstrap/api.py
> +        fcm_client_config[key] = getattr(settings, attr) if hasattr(settings, attr) else None
Also much nicer! I actually did what I think simplifies it even more, just building the whole dict as a literal in the return statement...

2021-05-11 07:48 UTC, layla19 commented on sync.py
> +    return subprocess.run(['grep', 'docker', '/proc/1/cgroup'], stdout=subprocess.DEVNULL).returncode == 0
I'm fine with both options, and I think it is more stable than checking for the environment so thumbsup for that. And thanks for the hint to the docker setup!

Still I'd like to point out that the name `sync.py` doesn't really explain what the script does, as a new developer you have to read the actual script to find out. So splitting the script into something like `install-dependencies` and `install-hooks` might fix that. I can see the advantage that currently there is only one script that does all the things for the setup to be completed. Maybe there could be a wrapping script then for the local setup, but I am not sure if that will make it any easier to understand at this point. So I'm also fine with `--no-hooks`.

2021-05-11 08:56 UTC, layla19 approved these changes

2021-05-11 10:42 UTC, merged